defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  
  
hydra:  
  output_subdir: null  
  run:  
    dir: .

get_web_data:
  active: True
  headers: {'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.76 Safari/537.36'}
  muscle_url: 'https://en.wikipedia.org/wiki/List_of_skeletal_muscles_of_the_human_body'
  exercises_url: 'https://strengthlevel.com/strength-standards'
  calculator_url: 'https://strengthlevel.com/'

web_scraper:
  active: True
  headers: {'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.76 Safari/537.36'}
  muscle_url: "https://en.wikipedia.org/wiki/List_of_skeletal_muscles_of_the_human_body"
  exercises_url: "https://exrx.net/Lists/Directory"
  calculator_url: 'https://strengthlevel.com/'